### PR TITLE
Improovments : ZéroTwó#5019

### PR DESCRIPTION
**Pull request by oOHiyoriOo**
I tried to improve visuals, support for nginx and a more appealing logging.
Added Options to control the logging a bit better and improve the usage with NGINX as reverse proxy

### CODE REVIEW

**Comment by oOHiyoriOo** [comment]
I tried to add a bit more "security" to it, as I saw weird requests on my Server, which seemed like someone was trying to kind of crawling the server and it's packs.
I know it might not be needed, as he would have to guess a right md5 hash, but why let the system look that up if we can instantly reject it because of user-agent 😎 
the default settings just warn the admin that a weird user agent has downloaded something, so it shouldn't break anything.
Rejection can be turned on if wanted, tho.

**Comment by Th0rgal** [comment]
Hey thanks for your work, it's pretty cool, I'm sorry I missed it. I think the nginx part is not required anymore because it is setup via docker. Cool idea for checking the user argent, what's the user agent of Minecraft?

**Comment by oOHiyoriOo** [comment]
Hi, User Agent was something like Minecraft Java.* instead of the * is the version.
You're right NGINX setting is not needed anymore, should i remove it?

**Comment by oOHiyoriOo** [comment]
Hey, I fixed all issues that prevented merging, hope that helps.
Also tested building process and running, which both works 👍

**Pull request merged**
